"""Make entities auditable

Revision ID: 1dee6dc7a2a3
Revises: c05bd4349445
Create Date: 2025-12-06 21:10:24.010972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dee6dc7a2a3'
down_revision: Union[str, Sequence[str], None] = 'c05bd4349445'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when created'))
    op.add_column('products', sa.Column('last_modified_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was last modified'))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when created'))
    op.add_column('users', sa.Column('last_modified_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was last modified'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_modified_at')
    op.drop_column('users', 'created_at')
    op.drop_column('products', 'last_modified_at')
    op.drop_column('products', 'created_at')
    # ### end Alembic commands ###
